'use strict';
window.JG_COMBOS = [
  {id:'carnivoro',name:'Carnívoro',image:'seleccion-carnes',tag:'Para los amantes de la carne',description:'Una selección de res, cerdo y pollo para disfrutar de la variedad.',price:230000,items:['1 lb. de filete de pechuga','1 lb. de carne de cerdo','2 lb. de pierna pernil','1 lb. de alitas','1 lb. de costilla ahumada','1 lb. de tocino','2 lb. de pechuga entera','1 lb. de chuleta de cerdo','1 lb. de carne molida','1 lb. de sobrebarriga','1 lb. de goulash','1 lb. de carne fina','1 lb. de costilla de res','1 salsa']},
  {id:'impacto',name:'Impacto',image:'parrilla-mixta',tag:'Variedad que se disfruta',description:'Punta de anca, pollo criollo y cortes para cambiar de sabor cada día.',price:190000,items:['1 lb. de filete de pechuga','1 lb. de punta de anca','1 lb. de goulash','1 lb. de sobrebarriga','2 lb. de pollo criollo','1 lb. de costilla de res','1 lb. de milanesa','1 lb. de alitas','1 lb. de costilla de cerdo','1 lb. de tocino','1 lb. de carne molida']},
  {id:'master',name:'Master',image:'parrilla-flotante',tag:'Una mesa con más posibilidades',description:'Carnes, mariscos y acompañamientos en una misma selección.',price:170000,items:['1 lb. de carne fina','1 cazuela de mariscos','2 lb. de pollo (muslo o colombina)','1 lb. de goulash','8 nuggets de pollo','1 lb. de costilla de res','1 lb. de costilla ahumada','1 lb. de tocino carnudo','1 lb. de molida especial','1 lb. de alitas','3 unidades de hamburguesas','1 lb. de yuca o patacones','½ lb. de jamón tajado','½ lb. de queso tajado']},
  {id:'elite',name:'Élite',image:'asado',tag:'El combo y sus complementos',description:'Carnes, arepas, adobos y acompañamientos para combinar a tu gusto.',price:160000,items:['1 lb. de carne de cerdo','1 lb. de costilla de res','1 paquete de hamburguesas apanadas','1 lb. de carne molida','1 lb. de costilla ahumada','2 lb. de muslos o colombinas','1 sobre de salsa','1 frasco de ajo','1 lb. de tocino carnudo','1 lb. de papa francesa','1 paquete de arepas de queso','1 paquete de arepas de maíz','1 frasco de adobo de carne','½ lb. de jamón ahumado','½ lb. de queso doble']},
  {id:'junior',name:'Junior',image:'pollo',tag:'Pequeño nombre. Gran selección.',description:'Mariscos, pollo y carnes con opciones para acompañar.',price:110000,items:['1 cazuela de mariscos','1 lb. de filete de pechuga','8 nuggets de pollo','1 lb. de costilla ahumada','1 lb. de tocino carnudo','1 lb. de molida especial','1 lb. de alitas','3 unidades de hamburguesas','1 lb. de yuca o patacones']},
  {id:'relampago',name:'Relámpago',image:'parrilla-atardecer',tag:'Sabor para tu próxima ocasión',description:'Res, pollo, ahumados y complementos para armar tu mesa.',price:160000,items:['1 lb. de filete de pechuga','1 lb. de carne fina','2 lb. de pollo','1 lb. de sobrebarriga','1 lb. de costilla de res','1 lb. de costilla ahumada','1 lb. de molida especial','1 lb. de papa a la francesa','½ lb. de jamón tajado','½ lb. de queso tajado','2 paquetes de arepas','2 unidades de especias','1 salsa']},
  {id:'premium',name:'Premium',image:'res',tag:'Para disfrutar cada elección',description:'Una combinación de cortes, pollo y acompañamientos para compartir.',price:180000,items:['1 lb. de carne fina','2 lb. de pollo','1 lb. de alitas','1 lb. de sobrebarriga','1 lb. de costilla de res','1 lb. de costilla ahumada','1 lb. de tocino carnudo','1 lb. de molida especial','1 lb. de filete de pechuga','½ lb. de jamón tajado','½ lb. de queso tajado','2 paquetes de arepas','2 especias','1 lb. de papa francesa','1 salsa']},
  {id:'familiar',name:'Familiar',image:'familia',tag:'Los buenos momentos se comparten',description:'Res, cerdo, pollo y complementos para reunir a los tuyos.',price:180000,items:['1 lb. de carne de cerdo','1 lb. de carne fina','2 lb. de pollo','1 lb. de goulash','1 lb. de sobrebarriga','1 lb. de costilla de res','1 lb. de costilla ahumada','1 lb. de tocino carnudo','1 lb. de molida especial','1 lb. de papa francesa','½ lb. de jamón tajado','½ lb. de queso tajado','2 paquetes de arepas','2 unidades de especias','1 salsa']}
];

